/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/github.glb')
  return (
    <group scale={[2,2,2]} rotation={[0,0,Math.PI]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} rotation={[-1.59, 0, 0]} scale={[0.01, 0.0015, 0.01]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-0.04, -0.06, 0.22]} rotation={[-1.58, 0, 0]} scale={[1.29, 1, 1.31]} />
    </group>
  )
}

useGLTF.preload('/github.glb')
