/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gmail.glb')
  return (
    <group rotation={[0,-Math.PI/2,0]} scale={[3,3,3]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} rotation={[-Math.PI, 0, 0]} scale={[-0.12, -0.49, -1.41]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[0.14, 0, 0.94]} rotation={[1.56, 0, -1.56]} scale={[0.35, 1, 0.4]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.004']} position={[0.13, -0.27, 0.77]} rotation={[1.57, -0.03, -1.57]} scale={[0.8, 1, 0.8]} />
    </group>
  )
}

useGLTF.preload('/gmail.glb')
