/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/linkedin.glb')
  return (
    <group rotation={[0,-Math.PI/2,0]} scale={[3,3,3]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} rotation={[-Math.PI, 0, 0]} scale={[-0.18, -1, -1]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.002']} position={[0.19, 0, 0]} rotation={[1.55, 0, -1.57]} />
    </group>
  )
}

useGLTF.preload('/linkedin.glb')
