/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Next({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/next.glb')
  return (
    <group scale={[2,2,2]} position={[0,0.5,0]} rotation={[0,-Math.PI/2,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} rotation={[-Math.PI, 0, 0]} scale={[-0.25, -1, -1]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[0.32, -0.49, 0.68]} rotation={[1.57, 0.04, -1.55]} scale={[1.62, 1, 1.52]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.003']} position={[0.29, -1.36, 0.56]} rotation={[1.57, 0.01, -1.6]} scale={[0.42, 1, 0.49]} />
    </group>
  )
}

useGLTF.preload('/next.glb')
