/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ReactModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/react.glb')
  return (
    <group  scale={[1,1,1]} rotation={[0,-Math.PI/2,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.001']} rotation={[-0.85, 0, 0]} scale={[1.33, 0.92, 2.15]} />
      <mesh geometry={nodes.Torus001.geometry} material={materials['Material.002']} position={[-0.01, 0.04, 0.13]} rotation={[0.88, 0, 0]} scale={[1.33, 0.94, 2.21]} />
      <mesh geometry={nodes.Torus002.geometry} material={materials['Material.003']} scale={[2.24, 1, 1.9]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.005']} position={[0, 1.56, 1.13]} rotation={[1.58, 0.06, -1.66]} scale={[0.92, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/react.glb')
